name: Check

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v20
        with:
          source-url: "https://install.lix.systems/lix/lix-installer-x86_64-linux"
      - name: Check flake
        run: nix flake check -L 
