[package]
name = "{{ cookiecutter.project_slug }}"
version = "0.1.0"
edition = "2024"
description = "{{ cookiecutter.description }}"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
